// @generated by build_interlinear.mjs - do not edit
pub fn book_bytes(abbrev: &str) -> Option<&'static [u8]> {
    match abbrev {
        "Matt" => Some(include_bytes!("../assets/bible/ilg/greek/Matt.json.gz")),
        "Mark" => Some(include_bytes!("../assets/bible/ilg/greek/Mark.json.gz")),
        "Luke" => Some(include_bytes!("../assets/bible/ilg/greek/Luke.json.gz")),
        "John" => Some(include_bytes!("../assets/bible/ilg/greek/John.json.gz")),
        "Acts" => Some(include_bytes!("../assets/bible/ilg/greek/Acts.json.gz")),
        "Rom" => Some(include_bytes!("../assets/bible/ilg/greek/Rom.json.gz")),
        "1Cor" => Some(include_bytes!("../assets/bible/ilg/greek/1Cor.json.gz")),
        "2Cor" => Some(include_bytes!("../assets/bible/ilg/greek/2Cor.json.gz")),
        "Gal" => Some(include_bytes!("../assets/bible/ilg/greek/Gal.json.gz")),
        "Eph" => Some(include_bytes!("../assets/bible/ilg/greek/Eph.json.gz")),
        "Phil" => Some(include_bytes!("../assets/bible/ilg/greek/Phil.json.gz")),
        "Col" => Some(include_bytes!("../assets/bible/ilg/greek/Col.json.gz")),
        "1Thess" => Some(include_bytes!("../assets/bible/ilg/greek/1Thess.json.gz")),
        "2Thess" => Some(include_bytes!("../assets/bible/ilg/greek/2Thess.json.gz")),
        "1Tim" => Some(include_bytes!("../assets/bible/ilg/greek/1Tim.json.gz")),
        "2Tim" => Some(include_bytes!("../assets/bible/ilg/greek/2Tim.json.gz")),
        "Titus" => Some(include_bytes!("../assets/bible/ilg/greek/Titus.json.gz")),
        "Phlm" => Some(include_bytes!("../assets/bible/ilg/greek/Phlm.json.gz")),
        "Heb" => Some(include_bytes!("../assets/bible/ilg/greek/Heb.json.gz")),
        "Jas" => Some(include_bytes!("../assets/bible/ilg/greek/Jas.json.gz")),
        "1Pet" => Some(include_bytes!("../assets/bible/ilg/greek/1Pet.json.gz")),
        "2Pet" => Some(include_bytes!("../assets/bible/ilg/greek/2Pet.json.gz")),
        "1John" => Some(include_bytes!("../assets/bible/ilg/greek/1John.json.gz")),
        "2John" => Some(include_bytes!("../assets/bible/ilg/greek/2John.json.gz")),
        "3John" => Some(include_bytes!("../assets/bible/ilg/greek/3John.json.gz")),
        "Jude" => Some(include_bytes!("../assets/bible/ilg/greek/Jude.json.gz")),
        "Rev" => Some(include_bytes!("../assets/bible/ilg/greek/Rev.json.gz")),
        "Gen" => Some(include_bytes!("../assets/bible/ilg/hebrew/Gen.json.gz")),
        "Exod" => Some(include_bytes!("../assets/bible/ilg/hebrew/Exod.json.gz")),
        "Lev" => Some(include_bytes!("../assets/bible/ilg/hebrew/Lev.json.gz")),
        "Num" => Some(include_bytes!("../assets/bible/ilg/hebrew/Num.json.gz")),
        "Deut" => Some(include_bytes!("../assets/bible/ilg/hebrew/Deut.json.gz")),
        "Josh" => Some(include_bytes!("../assets/bible/ilg/hebrew/Josh.json.gz")),
        "Judg" => Some(include_bytes!("../assets/bible/ilg/hebrew/Judg.json.gz")),
        "Rut" => Some(include_bytes!("../assets/bible/ilg/hebrew/Rut.json.gz")),
        "1Sam" => Some(include_bytes!("../assets/bible/ilg/hebrew/1Sam.json.gz")),
        "2Sam" => Some(include_bytes!("../assets/bible/ilg/hebrew/2Sam.json.gz")),
        "1Kgs" => Some(include_bytes!("../assets/bible/ilg/hebrew/1Kgs.json.gz")),
        "2Kgs" => Some(include_bytes!("../assets/bible/ilg/hebrew/2Kgs.json.gz")),
        "1Chr" => Some(include_bytes!("../assets/bible/ilg/hebrew/1Chr.json.gz")),
        "2Chr" => Some(include_bytes!("../assets/bible/ilg/hebrew/2Chr.json.gz")),
        "Ezra" => Some(include_bytes!("../assets/bible/ilg/hebrew/Ezra.json.gz")),
        "Neh" => Some(include_bytes!("../assets/bible/ilg/hebrew/Neh.json.gz")),
        "Est" => Some(include_bytes!("../assets/bible/ilg/hebrew/Est.json.gz")),
        "Job" => Some(include_bytes!("../assets/bible/ilg/hebrew/Job.json.gz")),
        "Ps" => Some(include_bytes!("../assets/bible/ilg/hebrew/Ps.json.gz")),
        "Prov" => Some(include_bytes!("../assets/bible/ilg/hebrew/Prov.json.gz")),
        "Eccl" => Some(include_bytes!("../assets/bible/ilg/hebrew/Eccl.json.gz")),
        "Song" => Some(include_bytes!("../assets/bible/ilg/hebrew/Song.json.gz")),
        "Isa" => Some(include_bytes!("../assets/bible/ilg/hebrew/Isa.json.gz")),
        "Jer" => Some(include_bytes!("../assets/bible/ilg/hebrew/Jer.json.gz")),
        "Lam" => Some(include_bytes!("../assets/bible/ilg/hebrew/Lam.json.gz")),
        "Ezek" => Some(include_bytes!("../assets/bible/ilg/hebrew/Ezek.json.gz")),
        "Dan" => Some(include_bytes!("../assets/bible/ilg/hebrew/Dan.json.gz")),
        "Hos" => Some(include_bytes!("../assets/bible/ilg/hebrew/Hos.json.gz")),
        "Joel" => Some(include_bytes!("../assets/bible/ilg/hebrew/Joel.json.gz")),
        "Amos" => Some(include_bytes!("../assets/bible/ilg/hebrew/Amos.json.gz")),
        "Obad" => Some(include_bytes!("../assets/bible/ilg/hebrew/Obad.json.gz")),
        "Jon" => Some(include_bytes!("../assets/bible/ilg/hebrew/Jon.json.gz")),
        "Mic" => Some(include_bytes!("../assets/bible/ilg/hebrew/Mic.json.gz")),
        "Nah" => Some(include_bytes!("../assets/bible/ilg/hebrew/Nah.json.gz")),
        "Hab" => Some(include_bytes!("../assets/bible/ilg/hebrew/Hab.json.gz")),
        "Zeph" => Some(include_bytes!("../assets/bible/ilg/hebrew/Zeph.json.gz")),
        "Hag" => Some(include_bytes!("../assets/bible/ilg/hebrew/Hag.json.gz")),
        "Zech" => Some(include_bytes!("../assets/bible/ilg/hebrew/Zech.json.gz")),
        "Mal" => Some(include_bytes!("../assets/bible/ilg/hebrew/Mal.json.gz")),
        _ => None,
    }
}

pub fn is_greek_book(abbrev: &str) -> bool {
    matches!(abbrev, "Matt" | "Mark" | "Luke" | "John" | "Acts" | "Rom" | "1Cor" | "2Cor" | "Gal" | "Eph" | "Phil" | "Col" | "1Thess" | "2Thess" | "1Tim" | "2Tim" | "Titus" | "Phlm" | "Heb" | "Jas" | "1Pet" | "2Pet" | "1John" | "2John" | "3John" | "Jude" | "Rev")
}

pub fn strong_bytes_greek() -> &'static [u8] {
    include_bytes!("../assets/bible/ilg/strongs/greek.json.gz")
}

pub fn strong_bytes_hebrew() -> &'static [u8] {
    include_bytes!("../assets/bible/ilg/strongs/hebrew.json.gz")
}
